In [2]:
import pandas as pd

## example sentence rule

아래의 <span style="color:orange">example_sentence</span>와 같이 원하시는 tag를 입력하면

tag값에 해당되는 단어들로 치환되면서 문장과 해당하는 "BIO" tag값이 완성됩니다.  
태깅이 되는 단어들로 모든 단어들로 치환되는 것이 아니라,    
relationship tree를 기반으로 문장이 생성됩니다.

### relationship tree
relationship tree내에 어떤 내용이 있는지 설명하는 Cell 입니다.  
**<span style="color:orange">index_code</span>** column이 부모 코드입니다.  
부모 코드 뒤에는 다음에 해당되는 code만 올 수 있습니다.  
  
더 자세한 내용은 <span style="color:skyblue">dictionaries.py</span>를 참조해주세요.

In [5]:
relationship_tree = pd.read_csv("./data/rela_tree_data.csv")
relationship_tree

  index_code   0   1   2    3
0         CO  OT  BT  BQ   SZ
1         BE  OT  BT  BQ   SZ
2         TA  OT  BT  BQ   SZ
3         AD  OT  AT  BQ   SZ
4         FD  OT  FT  FQ  NaN
5         SD  ST  SZ  SQ  NaN
6         JU  JT  OT  BQ   SZ

### word dictionary
Word dictionary는 tag 값과 그에 해당하는 단어들을 나열하는 dictionary 입니다.  
문장에서 **<span style="color:orange">"index_code"</span>** column으로   
tag를 채운다면 tag 값이 단어값으로 치환됩니다.

In [8]:
word_dictionary = pd.read_csv("./data/word_dict_data.csv")
word_dictionary

,index_code,0,1,2,3,4,5,6,7,8,...,14,15,16,17,18,19,20,21,22,23
0,CO,아이스 아메리카노,아이스 라떼,아이스 카페 라떼,아이스 카푸치노,아이스 바닐라 라떼,아이스 헤이즐넛 라떼,아이스 카라멜 마끼아또,아메리카노 아이스,라떼 아이스,...,헤이즐넛 라떼 아이스,모카 아이스,카페 모카 아이스,아이스 아메리카노,아메리카노,카페 라떼,카페라떼,카푸치노,바닐라 라떼,헤이즐넛 라떼
1,BE,초코 라떼,고구마 라떼,녹차 라떼,딸기 라떼,미숫가루 라떼,밀크티,프라푸치노,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TA,유자차,레몬 티,캐모마일 티,페퍼민트 티,얼그레이 티,복숭아 아이스 티,레모나 아이스 티,아이스 티,애플 티,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SD,콜라,코카 콜라,사이다,스프라이트,탄산수,페리에,트레비,사이다,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,JU,사과 주스,애플 주스,스파클링 애플 주스,바나나 주스,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,AD,체리콕,모히또,레몬 에이드,청포도 에이드,자몽 에이드,폭탄 에이드,애플망고 에이드,블루레몬 에이드,애플 사이다,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,FD,샌드위치,치즈 김밥,소고기 김밥,볶은 김치 컵밥,치킨 마요 컵밥,스팸 마요 컵밥,버터 장조림 컵밥,낙지 콩나물 컵밥,순두부 찌개 컵밥,...,빙수,마카롱,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,JT,얼음을 같이 갈아서,껍질 채 갈아서,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,OT,시원하게,아이스,핫,뜨겁게,따뜻하게,얼음 없이,얼음 적게,얼음 보통,얼음 많이,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,AT,시럽 추가해 주세요,시럽 50%로 주세요,시럽 빼주세요,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,BT,바닐라 시럽 빼주세요,바닐라 시럽 빼줘,바닐라 시럽 추가,바닐라 시럽 추가 해주세요,헤이즐넛 시럽 빼주세요,헤이즐넛 시럽 빼줘,헤이즐넛 시럽 추가,카라멜 시럽 빼주세요,카라멜 시럽 빼줘,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,FT,크림치즈 추가,크림치즈 빼,딸기 잼 추가,딸기 잼 뺴,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,BQ,[NUM] 잔,[NUM] 개,[NUM],NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,SQ,[NUM] 캔,[NUM] 병,[NUM],NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,FQ,[NUM] 개,[NUM],NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NUM,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
example_sentence = '<CO|BE|JU|TA> <BT|ST|FT>주세요.'

example_df = pd.DataFrame(data = {"sentence":[example_sentence]})

### sentence generator instance 생성을 합니다.

In [9]:
from sentence_placeholder import sentence_placeholder

functor = sentence_placeholder()

### Tree 내용을 각 object에 load를 합니다.
이 때, 파일 이름을 입력하시면 됩니다.

In [10]:
functor.rela_tree_readcsv("data/rela_tree_data.csv")
functor.wordset_dic_readcsv("data/word_dict_data.csv")

## input과 결과물
sentence placeholder object를 call 하면  
해당하는 문장과("sent" column)과, 해당하는 문자 단위 BIO ner_tag가 생성됩니다.

In [13]:
functor(example_df)

,sent,ner_tags
0,아이스 아메리카노 바닐라 시럽 빼주세요주세요.,"[B-CO, I-CO, I-CO, I-CO, I-CO, I-CO, I-CO, I-C..."
1,아이스 아메리카노 바닐라 시럽 빼줘주세요.,"[B-CO, I-CO, I-CO, I-CO, I-CO, I-CO, I-CO, I-C..."
2,아이스 아메리카노 바닐라 시럽 추가주세요.,"[B-CO, I-CO, I-CO, I-CO, I-CO, I-CO, I-CO, I-C..."
3,아이스 아메리카노 바닐라 시럽 추가 해주세요주세요.,"[B-CO, I-CO, I-CO, I-CO, I-CO, I-CO, I-CO, I-C..."
4,아이스 아메리카노 헤이즐넛 시럽 빼주세요주세요.,"[B-CO, I-CO, I-CO, I-CO, I-CO, I-CO, I-CO, I-C..."
...,...,...
583,블랙퍼스트 카라멜 시럽 추가주세요.,"[B-TA, I-TA, I-TA, I-TA, I-TA, O, B-BT, I-BT, ..."
584,블랙퍼스트 샷 빼주세요주세요.,"[B-TA, I-TA, I-TA, I-TA, I-TA, O, B-BT, I-BT, ..."
585,블랙퍼스트 샷 빼줘주세요.,"[B-TA, I-TA, I-TA, I-TA, I-TA, O, B-BT, I-BT, ..."
586,블랙퍼스트 샷 추가 해주세요주세요.,"[B-TA, I-TA, I-TA, I-TA, I-TA, O, B-BT, I-BT, ..."
587,블랙퍼스트 샷 추가 해줘주세요.,"[B-TA, I-TA, I-TA, I-TA, I-TA, O, B-BT, I-BT, ..."